### ISSUE TITLE
VisibilityPlaceWorker Logging

### ISSUE THREAD

**Issue by GoldenArbiter** [feldoh/I-Aint-Building-That#15]
As discussed via steam, subj method appears to be doing excessive logging.
Since it has been mentioned that there is no logging calls in the method, this is likely a 'me' issue, but any assistance would be appreciated. 

```IAintBuildingThat.VisibilityPlaceWorker
UnityEngine.StackTraceUtility:ExtractStackTrace ()
Verse.Log:Message (string)
BetterCV.BetterCVUtil:isOverWall (Verse.BuildableDef)
BetterCV.BlocksConstruction:_Postfix (Verse.Thing,Verse.Thing,bool&)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition:RimWorld.GenConstruct.BlocksConstruction_Patch10 (Verse.Thing,Verse.Thing)
RimWorld.GenConstruct:FirstBlockingThing (Verse.Thing,Verse.Pawn)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition:RimWorld.WorkGiver_ConstructDeliverResourcesToFrames.JobOnThing_Patch1 (RimWorld.WorkGiver_ConstructDeliverResourcesToFrames,Verse.Pawn,Verse.Thing,bool)
RimWorld.WorkGiver_Scanner:HasJobOnThing (Verse.Pawn,Verse.Thing,bool)
RimWorld.JobGiver_Work/<>c__DisplayClass3_1:<TryIssueJobPackage>g__Validator|0 (Verse.Thing)
Verse.RegionProcessorClosestThingReachable:ProcessThing (Verse.Region,Verse.Thing)
Verse.RegionProcessorClosestThingReachable:RegionProcessor (Verse.Region)
Verse.RegionTraverser/BFSWorker:BreadthFirstTraverseWork (Verse.Region,Verse.RegionEntryPredicate,Verse.RegionProcessor,int,Verse.RegionType)
Verse.RegionTraverser:BreadthFirstTraverse (Verse.Region,Verse.RegionEntryPredicate,Verse.RegionProcessor,int,Verse.RegionType)
Verse.RegionTraverser:BreadthFirstTraverse (Verse.Region,Verse.RegionProcessorDelegateCache,int,Verse.RegionType)
Verse.GenClosest:RegionwiseBFSWorker_NewTemp (Verse.IntVec3,Verse.Map,Verse.ThingRequest,Verse.AI.PathEndMode,Verse.TraverseParms,System.Predicate`1<Verse.Thing>,System.Func`2<Verse.Thing, single>,int,int,single,int&,Verse.RegionType,bool,bool)
Verse.GenClosest:ClosestThingReachable_NewTemp (Verse.IntVec3,Verse.Map,Verse.ThingRequest,Verse.AI.PathEndMode,Verse.TraverseParms,single,System.Predicate`1<Verse.Thing>,System.Collections.Generic.IEnumerable`1<Verse.Thing>,int,int,bool,Verse.RegionType,bool,bool)
Verse.GenClosest:ClosestThingReachable (Verse.IntVec3,Verse.Map,Verse.ThingRequest,Verse.AI.PathEndMode,Verse.TraverseParms,single,System.Predicate`1<Verse.Thing>,System.Collections.Generic.IEnumerable`1<Verse.Thing>,int,int,bool,Verse.RegionType,bool)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition:RimWorld.JobGiver_Work.TryIssueJobPackage_Patch0 (RimWorld.JobGiver_Work,Verse.Pawn,Verse.AI.JobIssueParams)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition:Glue:AbiFixup<Verse.AI.ThinkResult RimWorld.JobGiver_Work:TryIssueJobPackage(Verse.Pawn, Verse.AI.JobIssueParams),Verse.AI.ThinkResult RimWorld.JobGiver_Work.TryIssueJobPackage_Patch0(RimWorld.JobGiver_Work, Verse.Pawn, Verse.AI.JobIssueParams)> (RimWorld.JobGiver_Work,Verse.AI.ThinkResult&,Verse.Pawn,Verse.AI.JobIssueParams)
Verse.AI.ThinkNode_PrioritySorter:TryIssueJobPackage (Verse.Pawn,Verse.AI.JobIssueParams)
Verse.AI.ThinkNode_Priority:TryIssueJobPackage (Verse.Pawn,Verse.AI.JobIssueParams)
Verse.AI.ThinkNode_Tagger:TryIssueJobPackage (Verse.Pawn,Verse.AI.JobIssueParams)
Verse.AI.ThinkNode_Subtree:TryIssueJobPackage (Verse.Pawn,Verse.AI.JobIssueParams)
Verse.AI.ThinkNode_Priority:TryIssueJobPackage (Verse.Pawn,Verse.AI.JobIssueParams)
Verse.AI.ThinkNode_Conditional:TryIssueJobPackage (Verse.Pawn,Verse.AI.JobIssueParams)
Verse.AI.ThinkNode_Priority:TryIssueJobPackage (Verse.Pawn,Verse.AI.JobIssueParams)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition:Verse.AI.Pawn_JobTracker.DetermineNextJob_Patch1 (Verse.AI.Pawn_JobTracker,Verse.ThinkTreeDef&,bool)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition:Glue:AbiFixup<Verse.AI.ThinkResult Verse.AI.Pawn_JobTracker:DetermineNextJob(Verse.ThinkTreeDef&, System.Boolean),Verse.AI.ThinkResult Verse.AI.Pawn_JobTracker.DetermineNextJob_Patch1(Verse.AI.Pawn_JobTracker, Verse.ThinkTreeDef&, System.Boolean)> (Verse.AI.Pawn_JobTracker,Verse.AI.ThinkResult&,Verse.ThinkTreeDef&,bool)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition:Verse.AI.Pawn_JobTracker.TryFindAndStartJob_Patch1 (Verse.AI.Pawn_JobTracker)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition:Verse.AI.Pawn_JobTracker.EndCurrentJob_Patch4 (Verse.AI.Pawn_JobTracker,Verse.AI.JobCondition,bool,bool)
Verse.AI.Pawn_JobTracker:JobTrackerTick ()
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition:Verse.Pawn.Tick_Patch3 (Verse.Pawn)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition:Verse.TickList.Tick_Patch2 (Verse.TickList)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition:Verse.TickManager.DoSingleTick_Patch6 (Verse.TickManager)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition:Verse.TickManager.TickManagerUpdate_Patch2 (Verse.TickManager)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition:Verse.Game.UpdatePlay_Patch2 (Verse.Game)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition:Verse.Root_Play.Update_Patch1 (Verse.Root_Play)```

**Comment by feldoh** [comment]
Unless I'm blind that stack trace doesn't even mention this mod at all. It seems to be from whatever BetterCV is. Google implies Better Vents but I'm not certain of that.

**Comment by GoldenArbiter** [comment]
Oh beans, I literally missed the first line. 
`IAintBuildingThat.VisibilityPlaceWorker`

My apologies, I was knee deep in sleeping pills when I posted this. I'll still take a look at better vents to see what's going on there. May be a weird interaction. May still be a me problem.

What exactly does `IAintBuildingThat.VisibilityPlaceWorker` call?

**Comment by feldoh** [comment]
The github is where all the code is ;) you can see every line. Specifically the visibility place worker is here:
https://github.com/feldoh/I-Aint-Building-That/blob/b55c8d36d686f7097eec832c29404471edb30593/1.5/Source/I_Aint_Building_That/VisibilityPlaceWorker.cs#L6

I highly recommend posting the entire log if you can rather than snippets, if you don't know what the problem is you may miss important sections ;) that said, I'm certain this has nothing to do with this mod, you can see from the code it only overrides a single function; the `IsBuildDesignatorVisible` and that only checks if a few keys are held down and checks some settings. The only log lines in the entire mod are once at startup to list what it's made hidable.

**Comment by feldoh** [comment]
Yeah, thought so, I've decompiled the DLL in better vents https://steamcommunity.com/sharedfiles/filedetails/?id=1430094853
![image](https://github.com/user-attachments/assets/3a3ac17c-b6df-4328-806b-d99d85c82924)
and you can immediately see it's logging for every place worker for every tick it's a clear bug in Better Vents

**Comment by feldoh** [comment]
It's just printing out the name of every single place worker that happens to be active every tick hence why you might assume it's this mod, because I've added a placeWorker. It's actually logging all of them not just mine.

**Comment by GoldenArbiter** [comment]
Seen; Just actually got to test stuff, and better vents is in fact the main culprit.
Better coolers (Same author) Has a similar issue, just a significantly reduced scale. Removing both mods removes the log spam.

I'll let the author of those mods know it's being weird. 
Is 'Log.Message' required for the output of the if on the next line? I don't know enough about what I'm going to assume is either Java, C++, or C#, but I feel like that could likely just be commented out, right?

I appreciate you looking in to this for me. While I may be technically competent, game-dev and decompiling things is not where those talents lay, lol.

**Comment by GoldenArbiter** [comment]
Nevermind; You've already let them know.
You're an absolute Gem, mate.

**Comment by feldoh** [comment]
> Is 'Log.Message' required for the output of the if on the next line?

Nope the log message is entirely independent. Also, it's C#

**Comment by GoldenArbiter** [comment]
Follow on question; What do you use to decompile/compile the DLLs?

**Comment by feldoh** [comment]
I use Jetbrains DotPeek to just peek around in a DLL or if it's a dependency I can just dig around in Rider.

**Comment by GoldenArbiter** [comment]
Roger; Thanks again for the help <3
